# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    working_directory: ~/tic-tac-toe
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm i --no-progress
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test -- --no-progress --single-run --code-coverage
      - run: npm run e2e -- --no-progress
      - run: npm run coverage
